controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /homepage
    controller: App\Controller\HomeController::index

article_show:
    path: /recettes
    controller: App\Controller\ArticleController::index

article_add:
    path: /add
    controller: App\Controller\ArticleController::edit

article_edit:
    path: /edit/{id}
    controller: App\Controller\ArticleController::edit
    requirements:
        id: '\d+'

article_remove:
    path: /remove/{id}
    controller: App\Controller\ArticleController::remove
    requirements:
        id: '\d+'

user_removeUser:
    path: /removeUser/{id}
    controller: App\Controller\UsersController::removeUser
    requirements:
        id: '\d+'

contact:
    path: /contact
    controller: App\Controller\HomeController::contact
        
comm_add:
    path: /addCom
    controller: App\Controller\CommentController::ajout

